# Generated by Django 2.1.15 on 2020-06-17 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='created_at',
            field=models.CharField(default='2020-06-17 10:57', max_length=100),
        ),
    ]
