# Generated by Django 2.1.15 on 2020-06-17 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('accounts', '0001_initial'),
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorite_actors',
            field=models.ManyToManyField(blank=True, related_name='users', to='movies.Actor'),
        ),
        migrations.AddField(
            model_name='user',
            name='favorite_directors',
            field=models.ManyToManyField(blank=True, related_name='users', to='movies.Director'),
        ),
        migrations.AddField(
            model_name='user',
            name='favorite_movies',
            field=models.ManyToManyField(blank=True, related_name='users', to='movies.Movie'),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
