# Generated by Django 2.1.15 on 2020-06-17 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200617_0937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='favorite_actors',
        ),
        migrations.RemoveField(
            model_name='user',
            name='favorite_directors',
        ),
    ]
